### ISSUE TITLE
Add support for --no-fail-on-empty-changeset

### ISSUE THREAD

**Issue by chucklam** [CircleCI-Public/aws-sam-serverless-orb#15]
## What would you like to be added

`sam deploy` supports the `--no-fail-on-empty-changeset` option. I want this orb to support that too.

Right now, if there's no change for `sam` to deploy, it fails loudly with an exit code 1, which in turn causes CircleCI to mark the job as failed. This option would silence that, as having nothing to deploy shouldn't fail the build.

## Why is this needed

This [issue](https://github.com/awslabs/serverless-application-model/issues/71) in AWS goes into more detail on why they added the `--no-fail-on-empty-changeset` option to `sam deploy` to start with. Basically failing on no change doesn't make sense in a CI/CD pipeline.

I can make a PR to solve this issue. One thing I want to get feedback though is whether to make  `--no-fail-on-empty-changeset` the default. Personally I think that's the sensible thing to do for a CI/CD pipeline. Having said that, I can also see it could be confusing/bad form to change default behavior.

**Comment by JarmBlueOak** [comment]
Agree that this would be useful to have as currently trying to find a way around this, perhaps not as a default though just as an additional parameter on sam/deploy command.

**Comment by timoha** [comment]
I think this should be the default. The deploy command should be idempotent.
