### ISSUE TITLE
Upgrade to aws-cli-1.1.0 orb

### ISSUE THREAD

**Issue by simonratner** [CircleCI-Public/aws-sam-serverless-orb#16]
## What would you like to be added

Upgrade dependency to aws-cli-1.1.0.

## Why is this needed

Use awscli2, amongst other improvements and a "stable" release: https://circleci.com/orbs/registry/orb/circleci/aws-cli

**Comment by KyleTryon** [comment]
Resolved by #22. Now available in version 2.0.0. Thank you.
https://circleci.com/orbs/registry/orb/circleci/aws-sam-serverless?version=2.0.0
