### ISSUE TITLE
`sam package` not packing the built files when specifying the template-file option

### ISSUE THREAD

**Issue by shunwen** [CircleCI-Public/aws-sam-serverless-orb#18]
### Orb version

1.0.1

### What happened

Orb command **build** requires a `template` parameter and always pass it to the **package** step, where the `sam package` command packs files base on `CodeUri` in the given template instead of the folder generated in the `build` step.

### Expected behavior

`sam package` runs against the built files. 

#### Possible solution: 

1. Pass `./.aws-sam/build/<<parameters.template>>` or `<<parameters.build-dir>>/<<parameters.template>>` to `sam package` 
2. Suggest users build requirements layer instead of relying on `requirements.txt`, more like a workaround for now.

**Comment by timoha** [comment]
Hitting the same issue.
The thing is that the `deploy` job shouldn't even need to call `package`. The documentation of `sam` says it should be enough to just call `sam build` and then `sam deploy`. The template file indeed only needs to be passed on `sam build` stage.

**Comment by dsayling** [comment]
We are working on a larger update to include this fix in #25 - thank you for your patience
