### ISSUE TITLE
Feature request: Pass environment variables to a container

### ISSUE THREAD

**Issue by yuokada** [CircleCI-Public/aws-sam-serverless-orb#42]
## Describe Request:

When executing `sam build`,  I would like to pass environment variables to a build container.
In my case, I need to pass environment variables for the artifactory private maven repository to a container.

## Examples:

There are 2 ways to pass environment variables in aws sam CLI.
I think it's simple to support taking the `container-env-var-file` option compared to the other way.

```
To build with environment variables passed to the build container from the command line
$ sam build --use-container --container-env-var Function1.GITHUB_TOKEN=<token1> --container-env-var GLOBAL_ENV_VAR=<global-token>

To build with environment variables passed to the build container from a file
$ sam build --use-container --container-env-var-file <env-file.json>
```

## Supporting Documentation Links:
- https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-build.html
- [Container environment variable file](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-build.html#serverless-sam-cli-using-container-environment-file)

**Comment by KyleTryon** [comment]
While the file would be easier to implement for the orb, I wonder how users would get the json file into the job. You could base64 encode the file, add as an env_var and then write to a file, but thats a bit convoluted.

With the first option, we could do something like:

```yaml
sam/build:
  container-vars: Function1.GITHUB_TOKEN=$VAR1, GLOBAL_ENV_VAR=$VAR2
```

or

```yaml
sam/build:
  container-vars: |
      Function1.GITHUB_TOKEN=$VAR1
      GLOBAL_ENV_VAR=$VAR2
```

**Comment by brivu** [comment]
Hey @yuokada, 

Thank you for supplying us with the documentation. We're going to be working on all updating this orb this quarter so expect this to be released in the next 6 - 8 weeks. 

Thanks again!
Brian
