### ISSUE TITLE
Add --parallel parameter

### ISSUE THREAD

**Issue by rsorelli-hedgepoint** [CircleCI-Public/aws-sam-serverless-orb#52]
## Describe Request:
This orb doesn't allow using the parameter --parallel to build multiple lambdas at the same time

## Examples:
sam build --template template.yaml --parallel

## Supporting Documentation Links:
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-build.html

**Comment by brivu** [comment]
Hey @rsorelli-hedgepoint! 

Thanks for opening this issue. I am working adding a `build_arguments` parameter to the `sam/build` command and sam/deploy` job that will enable you to add additional flags to the `sam build` command like `--parallel`. 

We'll be looking to cut a new major release soon, which will include this feature. 

Thank you!

Best, 
Brian
