### ISSUE TITLE
Additional args doesn't seem to work

### ISSUE THREAD

**Issue by zhangmatthieu** [CircleCI-Public/aws-sam-serverless-orb#53]
## Orb version:

4.0.0

## What happened:

When we use the `additional-args` parameter, it seems to be ignored. When we don't use it, a `''` is appended to the `sam deploy` command which can break the parameter-overrides parameter (see https://github.com/CircleCI-Public/aws-sam-serverless-orb/issues/50).

## Expected behavior:

It should be the opposite. `additional-args` parameter should be used when used and should be ignored when not used.

## Additional Information:

It seems to be due to the `if [ -z "$SAM_PARAM_ADDITIONAL_ARGS" ]; then` in the `deploy` script which should have a `-n` instead of a `-z`

**Comment by lucastonelli** [comment]
Any update on this bug? I'm looking forward to using this parameter 😝
